config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  resources :locations do
      resources :comments
  end

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
    has_many :comments, dependent: :destroy, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @location = Location.find(params[:location_id])
    @comment = @location.comments.create(comment_params)
    redirect_to location_path(@location)
  end
   

  
  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @location = Location.find(params[:location_id])
    @comment = @location.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment successfully deleted!"
    redirect_to location_path(@location)
    
    #Not sure if we need this anymore. - Jack
    
      #@comment.destroy
        #respond_to do |format|
        #format.html { redirect_to location_path, notice: 'Comment was successfully destroyed.' }
        #format.json { head :no_content }
      #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #TODO - Replace 1 with random id
      @location = Location.order("RANDOM()").second
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /locations
  # GET /locations.json
  def index
    @location = Location.order(sort_column + ' ' + sort_direction)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show 
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to edit_location_path, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy
  
    redirect_to action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:title, :rating, :longitude, :latitude, :zoom)
    end
    
    def location_builder(long, lat)
      puts long
      return "https://maps.googleapis.com/maps/api/staticmap?center="
    end
    
    def sort_column
      Location.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.location %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Confirm comment deletion?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Location:</strong>
  <%= @comment.location %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<!-- Location Container -->
<div class="container" id="location">
  <div class="row">
    <div class="col-4" id="title">
      <h1>
        <%= @location.title %>
      </h1>
    </div>
    
    <!-- Random/New Location Buttons -->
  <div class="row">
    <div class="col-12" style="margin-top:6px">
      <%= link_to 'Random Location', root_path, class: "btn btn-primary" %>
      <button class="new-location" style="vertical-align:middle" onclick="window.location.href='/locations/new'"><span>+ </span></a></button>
    </div>
  </div>
<!-- End of location contianer -->

  <div class="container">
    <div class="row">
      <div class="col-6">
        <iframe width="600" height="450" frameborder="0" style="border:0" 
          src="https://www.google.com/maps/embed/v1/view?zoom=<%=@location.zoom%>
          &center=<%=@location.longitude%>, <%=@location.latitude%>
          &key=AIzaSyDd1D5MfjxI4rFeElwebLzssyqgkfPHpLc
          &maptype=satellite" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>
  </div>
  

<!-- User Rating -->
  <div class="row">
    <div class="col-6">
      <% (1..@location.rating).each do |i| %>
        <%= image_tag '/assets/star.png', :class => "rating_star" %>
      <% end %><br><br>
    </div>
  </div>

</div>



<!-- Comments Container -->
<div class="container" id="comments">
  <div class="row">
    <div class="col-6">
      <h2>Comments</h2>
        <div id="wrapper">
          <div class="scrollbar" id="style-default">
            <div class="force-overflow">
              <% if @location.comments.each do |comment| %>
                <p>
                  <strong>Commenter: </strong>
                    <%= comment.commenter %>
                        <!-- Comment Timestamp -->
                       <i><span style="color:gray; font-size:12px"> - <%= time_ago_in_words(comment.created_at) %> ago.</span></i>
                </p>
                <p>  
                  <strong>Comment:</strong>
                    <%= comment.body %>
                      <!-- Delete Comment Button -->
                      <%= button_to 'Delete Comment', location_comment_url(@location, comment), method: :delete, data: { confirm: 'confirm comment deletion?' }, :class => "btn btn-danger btn-sm" %> 
                        <% end.empty? %>
                          <h5>Sorry, there are no comments at the moment! Add one below!</h5>
                </p>
                <% end %>
            </div>
          </div>
        </div>
        
      <!-- Comment Submission Form -->
    
      <h2>Add a comment: </h2>
        <div class="container">
          <%= form_for([@location, @location.comments.build]) do |f| %>
            <p>
              <%= f.label :commenter  %><br>
              <%= f.text_field :commenter %>
            </p>
            <p>
              <%= f.label :body  %><br>
              <%= f.text_field :body %>
            </p>
            <p>
              <%= f.submit :Submit, class: 'btn btn-info'%>
            </p>
              
            <% end %>
        </div>
    </div>
  </div>
<!--End of comment contianer -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="jquery-3.2.0.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="img-container"></div>
      <div class="blur"></div>
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded" id="navcolor">
          <div class="container" id="navbar">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="../../home/index" id="navbaricon" class="d-inline-block align-top"><img src="https://lh3.googleusercontent.com/-dkgKtmVl2D4/WO24tRzeycI/AAAAAAAALQg/qEsPiqFMmbY2oWv6KlfzfyGJbS2maFr6wCJoC/w530-h153-p-rw/greatspot.png" height=35px width=130px/></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                   <button class="button" style="vertical-align:middle"><a href="/locations" style="color: #fff;"><span>All Locations</span></button></a>
                  </li>
                </li>
                <!-- <a class="nav-link" href="#">All Locations <span class="sr-only">(current)</span></a> -->
            </div>
          <!-- End of navbar contianer -->
          </div>
        </nav>
      <%= yield %>
    <div id="footer"><img src="https://lh3.googleusercontent.com/-l4QfpI2zgVc/WO60eHfyuTI/AAAAAAAALYE/dt0esRdH_jIxU6Afi9RFQs2gueo0M6E3gCL0B/w310-d-h94-p-rw/greatspotbottom.png"/></div>
  </body>
</html>

app/views/locations/_form.html.erb
<div class="container">
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, :required =>"true" %>
  </div>
    <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, :required =>"true" %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :required =>"true" %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating, :required =>"true" %>
  </div>
  <div class="field">
    <%= f.label :zoom%> Level 1-20; 1:World, 20:Building<br>
    <%= f.number_field :zoom, :required =>"true" %>
  </div>
  <br>
  <div>
    <%=  f.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

<% unless @location.longitude.blank? %>
  <div class="row">
    <div class="col-6">
      <iframe id="map" width="600" height="450" frameborder="0" style="border:0" 
        src="https://www.google.com/maps/embed/v1/view?zoom=<%=@location.zoom%>
        &center=<%=@location.longitude%>, <%=@location.latitude%>
        &key=AIzaSyDd1D5MfjxI4rFeElwebLzssyqgkfPHpLc
        &maptype=satellite" allowfullscreen>
      </iframe>
    </div>
  </div>
<% end %>
</div>

app/views/locations/edit.html.erb
<div class="container">
    <h1>Editing Location</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Show', @location, class: "btn btn-primary btn-sm" %> |
    <%= link_to 'Back', locations_path, class: "btn btn-warning btn-sm" %>
</div>

app/views/locations/index.html.erb
<div class="container">
  <div class="col-10">
    <p id="notice"><%= notice %></p>
      <h1>Listing Locations</h1>
        <table class="table pretty table-bordered table-striped table-hover">
          <thead class="thead-bg">
            <tr>
              <th class="alignment" scope="row"><%= sortable "id" %></th>
              <th class="alignment">Longitude</th>
              <th class="alignment">Latitude</th>
              <th class="header-text"><%= sortable "title" %></th>
              <th class="alignment header-text"><%= sortable "rating" %></th>
              <th class="alignment" colspan="3">Options</th>
            </tr>
          </thead>
          <tbody>
            <% @location.each do |location| %>
              <tr>
                <td align=center><%= location.id %></td>
                <td><%= location.longitude %></td>
                <td><%= location.latitude %></td>
                <td><%= location.title %></td>
                <td>
                  <% (1..location.rating).each do |i| %>
                    <%= image_tag '/assets/star.png', :class => "rating_star" %>
                  <% end %>
                </td>
                <td><%= link_to 'Show', location %></td>
                <td><%= link_to 'Edit', edit_location_path(location) %></td>
                <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Delete location?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <%= link_to 'New Location', new_location_path, class: "new_location", class: "btn btn-primary" %>
    <br>
    <br>
  </div>
</div>

app/views/locations/new.html.erb
<div class="container">
<h1>New Location</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', locations_path, class:"btn btn-danger btn-sm" %>
</div>

app/views/locations/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<!-- Location information -->
<h3>
  <strong>Title:</strong>
  <%= @location.title %>
</h3>

<h5>
  <strong>Longitude & Latitude:</strong>
  <%= @location.longitude %>, <%= @location.latitude %>
</h5>

<!-- Location google maps iframe -->
<div class="row">
  <div class="col-6">
    <iframe id="map" width="600" height="450" frameborder="0" style="border:0" 
      src="https://www.google.com/maps/embed/v1/view?zoom=<%=@location.zoom%>
      &center=<%=@location.longitude%>, <%=@location.latitude%>
      &key=AIzaSyDd1D5MfjxI4rFeElwebLzssyqgkfPHpLc
      &maptype=satellite" allowfullscreen>
    </iframe>
  </div>
</div>


<!-- User Rating -->
<div class="row container">
<% (1..@location.rating).each do |i| %>
<%= image_tag '/assets/star.png', :class => "rating_star" %>
<% end %>
</div>


<!-- Comments Container -->
<br>
<div id="comments">
  <div class="row">
    <div class="col-6">
      <h2>Comments</h2>
        <div id="wrapper">
          <div class="scrollbar" id="style-default">
            <div class="force-overflow">
              <% if @location.comments.each do |comment| %>
                <p>
                  <strong>Commenter: </strong>
                    <%= comment.commenter %>
                        <!-- Comment Timestamp -->
                       <i><span style="color:gray; font-size:12px"> - <%= time_ago_in_words(comment.created_at) %> ago.</span></i>
                </p>
                <p>  
                  <strong>Comment:</strong>
                    <%= comment.body %>
                      <!-- Delete Comment Button -->
                      <%= button_to 'Delete Comment', location_comment_url(@location, comment), method: :delete, data: { confirm: 'confirm comment deletion?' }, :class => "btn btn-danger btn-sm" %> 
                      <% end.empty? %>
                    <h5>Sorry, there are no comments at the moment! Add one <a href="#comment_anchor" data-no-turbolink>below</a>!</h5>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      <!-- Comment Submission Form -->
      <h2>Add a comment: </h2>
        <div class="container">
          <%= form_for([@location, @location.comments.build]) do |f| %>
            <p>
              <%= f.label :commenter  %><br>
              <%= f.text_field :commenter %>
            </p>  
            <p>
            <%= f.label :body  %><br>
            <%= f.text_field :body %>
            </p>
            <p>
            <%= f.submit %>
            </p>
          <% end %>
        </div>
      <div class="bbcontainer">
        <%=  link_to'Edit', edit_location_path(@location), class:"btn btn-primary btn-sm" %> |
        <%= link_to 'Back', locations_path, class:"btn btn-danger btn-sm"%>
      </div>
</div>